### ISSUE TITLE
jottit backup?

### ISSUE THREAD

**Issue by paucc** [madridrb/madridrb.org#16]
I'm continuing with the design of the views and I would love to be able to work with real text. Do we have a backup of the jottit web?

**Comment by kikito** [comment]
I am afraid there is no backup. The jottit people contacted me via twitter and told me that it could take some time to get jottit back up.

If you just need the data "to get an idea of the structure", then the latest terracismo on the github wiki is nearly the same as the jottit pages:

https://github.com/madridrb/madridrb.github.io/wiki/2014-07-31%3A-Terracismo.rb

It is only missing 3 things as far as I know:
- Speaker name (terracismos have no speakers)
- Speaker link (i.e twitter handle)
- Sponsor logos and links

In case it helps, I listed the Meeting fields on Issue #3

**Comment by paucc** [comment]
I wanted to have talk titles and description to get an idea of the min and max lengths. I will take the data from Vimeo. Do you make it longer on the vimeo description?

**Comment by kikito** [comment]
The Vimeo titles are the same as the jottit titles. You can take them from there, yes.

**Comment by paucc** [comment]
Great! I will do that.

**Comment by xuanxu** [comment]
You can also find all the info in the cached version of the site, google has the [homepage](http://webcache.googleusercontent.com/search?q=cache:4e5y59iBDSYJ:madridrb.jottit.com/+&cd=1&hl=en&ct=clnk&gl=es) and the [monthly pages](http://webcache.googleusercontent.com/search?q=cache:bNrOIxBRNFEJ:https://madridrb.jottit.com/abril_2014+&cd=3&hl=en&ct=clnk&gl=es).

**Comment by paucc** [comment]
That's true!
Google knows it all. :)

**Comment by kikito** [comment]
The cache seems to have expired, but I found the same things in The Internet Archive:
- [Root](http://web.archive.org/web/20140620171458/https://madridrb.jottit.com/)
- [Monthly](http://web.archive.org/web/20140801151429/https://madridrb.jottit.com/mayo_2014)
